### ISSUE TITLE
uncaughtError: read ECONRESET on using !next

### ISSUE THREAD

**Issue by BananaDev50** [ItsBanana/BananaBot#1]
(Just a reminder for myself)
If you run BananaBot on linux and you skip the current playing track an uncaughtError occurs and the bot crashes. I think the stream module of nodejs is different on linux distro's...

**Comment by BananaDev50** [comment]
The issue is still there apparently. Still only happened while hosting it on linux...
Gonna try the fix mentioned here fent/node-ytdl-core#65

**Comment by BananaDev50** [comment]
Ffs this error is killing meh...
(still only happening on linux...)

**Comment by ItsBanana** [comment]
Not pretty...but fixed here -> https://github.com/ItsBanana/BananaBot-Base/commit/7282dbf58a73c96ca54a7d2bab51bab6720deb25

**Comment by BananaDev50** [comment]
Okay the problem still isn't fixed :(
One way to fix it is by changing exitOnError to false in src/Bot.js of the bananabot-base module
